### ISSUE TITLE
MouseX::App via mousex-getopt-0.35.tar.gz and Getopt::Long::Descriptive V 0.099

### ISSUE THREAD

**Issue by ronsavage** [genehack/app-gitgot#46] opened 2015-03-03 21:34 UTC
It isn't possible to install App::GitGot V 1.22 with the above, which are pulled in automatically with cpanm. It seems the real problem is Getopt::Long::Descriptive.

**Comment by genehack** [comment] 2015-03-13 16:45
What error are you getting with Getopt::Long::Descriptive?

**Comment by ronsavage** [comment] 2015-03-13 22:53
See https://gist.github.com/ronsavage/c2cb241c488efa0a6f6f

**Comment by genehack** [comment] 2015-03-13 23:07
So, those look like pretty harmless whitespace-driven test failures to me. I would say you have two not-mutually-exclusive options:

1) force-install MouseX::Getopt
2) file a bug against MouseX::Getopt

My short-term plans for GitGot involve migrating away from Mouse usage completely, for what it's worth. 

I'm going to close this ticket, as this is not a bug in GitGot. Thanks!

**Closed by genehack** 2015-03-13 23:07 UTC
